#!/bin/sh

# if a module has a build dependency that is not in debian/alpine
# use this script to fetch/build/install them
#
# note that shared libraries produced as a result of this script will
# not be copied from the builder image to the resulting one, so you need to
# build them statically

# 下载第三方扩展模块nginx_upstream_check_module
echo "No prebuild stage required - all dependencies are satisfied already!"
# wget https://codeload.github.com/yaoweibin/nginx_upstream_check_module/zip/master
# git@github.com:yaoweibin/nginx_upstream_check_module.git
# unzip master 1>/dev/null
# ls -ld nginx_upstream_check_module-master

# 重新编译nginx，加入需要安装的模块：
# 为nginx打补丁：
# patch -p0 < ./nginx_upstream_check_module-master/check_1.16.1+.patch

# 添加模块
# ./configure --user=nginx --group=nginx --with-http_ssl_module --with-http_stub_status_module --prefix=/modules/ --add-module=./nginx_upstream_check_module-master

exit 0
